# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\code\Git\MarkDownEditor\CodeEditor\UI\SearchDialog.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(270, 365)
        Dialog.setMinimumSize(QtCore.QSize(260, 365))
        Dialog.setMaximumSize(QtCore.QSize(270, 365))
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.findComboBox = QtWidgets.QComboBox(Dialog)
        self.findComboBox.setMinimumSize(QtCore.QSize(0, 25))
        self.findComboBox.setMaximumSize(QtCore.QSize(16777215, 25))
        self.findComboBox.setEditable(True)
        self.findComboBox.setObjectName("findComboBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.findComboBox)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.replaceWithComboBox = QtWidgets.QComboBox(Dialog)
        self.replaceWithComboBox.setMinimumSize(QtCore.QSize(0, 25))
        self.replaceWithComboBox.setMaximumSize(QtCore.QSize(16777215, 25))
        self.replaceWithComboBox.setEditable(True)
        self.replaceWithComboBox.setObjectName("replaceWithComboBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.replaceWithComboBox)
        self.verticalLayout_4.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.forwardDirectionRadio = QtWidgets.QRadioButton(self.groupBox)
        self.forwardDirectionRadio.setObjectName("forwardDirectionRadio")
        self.verticalLayout.addWidget(self.forwardDirectionRadio)
        self.backwardDirectionRadio = QtWidgets.QRadioButton(self.groupBox)
        self.backwardDirectionRadio.setObjectName("backwardDirectionRadio")
        self.verticalLayout.addWidget(self.backwardDirectionRadio)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.allScopeRadio = QtWidgets.QRadioButton(self.groupBox_2)
        self.allScopeRadio.setObjectName("allScopeRadio")
        self.verticalLayout_2.addWidget(self.allScopeRadio)
        self.selectedLineScopeRadio = QtWidgets.QRadioButton(self.groupBox_2)
        self.selectedLineScopeRadio.setObjectName("selectedLineScopeRadio")
        self.verticalLayout_2.addWidget(self.selectedLineScopeRadio)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName("gridLayout")
        self.caseSensitiveOptionsCheckBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.caseSensitiveOptionsCheckBox.setObjectName("caseSensitiveOptionsCheckBox")
        self.gridLayout.addWidget(self.caseSensitiveOptionsCheckBox, 0, 0, 1, 1)
        self.wrapSearchOptionsCheckBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.wrapSearchOptionsCheckBox.setObjectName("wrapSearchOptionsCheckBox")
        self.gridLayout.addWidget(self.wrapSearchOptionsCheckBox, 0, 1, 1, 1)
        self.wholeWordOptionsCheckBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.wholeWordOptionsCheckBox.setObjectName("wholeWordOptionsCheckBox")
        self.gridLayout.addWidget(self.wholeWordOptionsCheckBox, 1, 0, 1, 1)
        self.incrementalOptionsCheckBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.incrementalOptionsCheckBox.setObjectName("incrementalOptionsCheckBox")
        self.gridLayout.addWidget(self.incrementalOptionsCheckBox, 1, 1, 1, 1)
        self.regularExpressionsOptionsCheckBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.regularExpressionsOptionsCheckBox.setTristate(False)
        self.regularExpressionsOptionsCheckBox.setObjectName("regularExpressionsOptionsCheckBox")
        self.gridLayout.addWidget(self.regularExpressionsOptionsCheckBox, 2, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setContentsMargins(0, -1, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.findButton = QtWidgets.QPushButton(self.frame)
        self.findButton.setMinimumSize(QtCore.QSize(90, 25))
        self.findButton.setMaximumSize(QtCore.QSize(90, 25))
        self.findButton.setObjectName("findButton")
        self.horizontalLayout_2.addWidget(self.findButton)
        self.replaceOrFindButton = QtWidgets.QPushButton(self.frame)
        self.replaceOrFindButton.setMinimumSize(QtCore.QSize(90, 25))
        self.replaceOrFindButton.setMaximumSize(QtCore.QSize(90, 25))
        self.replaceOrFindButton.setObjectName("replaceOrFindButton")
        self.horizontalLayout_2.addWidget(self.replaceOrFindButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.replaceButton = QtWidgets.QPushButton(self.frame)
        self.replaceButton.setMinimumSize(QtCore.QSize(90, 25))
        self.replaceButton.setObjectName("replaceButton")
        self.horizontalLayout_3.addWidget(self.replaceButton)
        self.replaceAllButton = QtWidgets.QPushButton(self.frame)
        self.replaceAllButton.setMinimumSize(QtCore.QSize(90, 25))
        self.replaceAllButton.setMaximumSize(QtCore.QSize(90, 25))
        self.replaceAllButton.setObjectName("replaceAllButton")
        self.horizontalLayout_3.addWidget(self.replaceAllButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.infoLabel = QtWidgets.QLabel(self.frame)
        self.infoLabel.setText("")
        self.infoLabel.setObjectName("infoLabel")
        self.horizontalLayout_4.addWidget(self.infoLabel)
        self.closeButton = QtWidgets.QPushButton(self.frame)
        self.closeButton.setMinimumSize(QtCore.QSize(90, 25))
        self.closeButton.setMaximumSize(QtCore.QSize(90, 25))
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_4.addWidget(self.closeButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout_4.addWidget(self.frame)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Find"))
        self.label_2.setText(_translate("Dialog", "Replace With"))
        self.groupBox.setTitle(_translate("Dialog", "Direction"))
        self.forwardDirectionRadio.setText(_translate("Dialog", "Forward"))
        self.backwardDirectionRadio.setText(_translate("Dialog", "Backward"))
        self.groupBox_2.setTitle(_translate("Dialog", "Scope"))
        self.allScopeRadio.setText(_translate("Dialog", "All"))
        self.selectedLineScopeRadio.setText(_translate("Dialog", "Selected Lines"))
        self.groupBox_3.setTitle(_translate("Dialog", "Options"))
        self.caseSensitiveOptionsCheckBox.setText(_translate("Dialog", "Case Sensitive"))
        self.wrapSearchOptionsCheckBox.setText(_translate("Dialog", "Wrap Search"))
        self.wholeWordOptionsCheckBox.setText(_translate("Dialog", "Whole Word"))
        self.incrementalOptionsCheckBox.setText(_translate("Dialog", "Incremental"))
        self.regularExpressionsOptionsCheckBox.setText(_translate("Dialog", "Regular Expressions"))
        self.findButton.setText(_translate("Dialog", "Find"))
        self.replaceOrFindButton.setText(_translate("Dialog", "Replace/Find"))
        self.replaceButton.setText(_translate("Dialog", "Replace"))
        self.replaceAllButton.setText(_translate("Dialog", "Replace All"))
        self.closeButton.setText(_translate("Dialog", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

